// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: draco.proto

#ifndef PROTOBUF_INCLUDED_draco_2eproto
#define PROTOBUF_INCLUDED_draco_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_draco_2eproto 

namespace protobuf_draco_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_draco_2eproto
namespace draco {
class pnc_msg;
class pnc_msgDefaultTypeInternal;
extern pnc_msgDefaultTypeInternal _pnc_msg_default_instance_;
class vr_teleop_msg;
class vr_teleop_msgDefaultTypeInternal;
extern vr_teleop_msgDefaultTypeInternal _vr_teleop_msg_default_instance_;
}  // namespace draco
namespace google {
namespace protobuf {
template<> ::draco::pnc_msg* Arena::CreateMaybeMessage<::draco::pnc_msg>(Arena*);
template<> ::draco::vr_teleop_msg* Arena::CreateMaybeMessage<::draco::vr_teleop_msg>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace draco {

// ===================================================================

class pnc_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:draco.pnc_msg) */ {
 public:
  pnc_msg();
  virtual ~pnc_msg();

  pnc_msg(const pnc_msg& from);

  inline pnc_msg& operator=(const pnc_msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  pnc_msg(pnc_msg&& from) noexcept
    : pnc_msg() {
    *this = ::std::move(from);
  }

  inline pnc_msg& operator=(pnc_msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const pnc_msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const pnc_msg* internal_default_instance() {
    return reinterpret_cast<const pnc_msg*>(
               &_pnc_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(pnc_msg* other);
  friend void swap(pnc_msg& a, pnc_msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline pnc_msg* New() const final {
    return CreateMaybeMessage<pnc_msg>(NULL);
  }

  pnc_msg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<pnc_msg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const pnc_msg& from);
  void MergeFrom(const pnc_msg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(pnc_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float est_base_joint_pos = 3;
  int est_base_joint_pos_size() const;
  void clear_est_base_joint_pos();
  static const int kEstBaseJointPosFieldNumber = 3;
  float est_base_joint_pos(int index) const;
  void set_est_base_joint_pos(int index, float value);
  void add_est_base_joint_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      est_base_joint_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_est_base_joint_pos();

  // repeated float est_base_joint_ori = 4;
  int est_base_joint_ori_size() const;
  void clear_est_base_joint_ori();
  static const int kEstBaseJointOriFieldNumber = 4;
  float est_base_joint_ori(int index) const;
  void set_est_base_joint_ori(int index, float value);
  void add_est_base_joint_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      est_base_joint_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_est_base_joint_ori();

  // repeated float joint_positions = 5;
  int joint_positions_size() const;
  void clear_joint_positions();
  static const int kJointPositionsFieldNumber = 5;
  float joint_positions(int index) const;
  void set_joint_positions(int index, float value);
  void add_joint_positions(float value);
  const ::google::protobuf::RepeatedField< float >&
      joint_positions() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_joint_positions();

  // repeated float des_com_pos = 6;
  int des_com_pos_size() const;
  void clear_des_com_pos();
  static const int kDesComPosFieldNumber = 6;
  float des_com_pos(int index) const;
  void set_des_com_pos(int index, float value);
  void add_des_com_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      des_com_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_des_com_pos();

  // repeated float act_com_pos = 7;
  int act_com_pos_size() const;
  void clear_act_com_pos();
  static const int kActComPosFieldNumber = 7;
  float act_com_pos(int index) const;
  void set_act_com_pos(int index, float value);
  void add_act_com_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      act_com_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_act_com_pos();

  // repeated float lfoot_pos = 8;
  int lfoot_pos_size() const;
  void clear_lfoot_pos();
  static const int kLfootPosFieldNumber = 8;
  float lfoot_pos(int index) const;
  void set_lfoot_pos(int index, float value);
  void add_lfoot_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      lfoot_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lfoot_pos();

  // repeated float rfoot_pos = 9;
  int rfoot_pos_size() const;
  void clear_rfoot_pos();
  static const int kRfootPosFieldNumber = 9;
  float rfoot_pos(int index) const;
  void set_rfoot_pos(int index, float value);
  void add_rfoot_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      rfoot_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rfoot_pos();

  // repeated float lfoot_ori = 10;
  int lfoot_ori_size() const;
  void clear_lfoot_ori();
  static const int kLfootOriFieldNumber = 10;
  float lfoot_ori(int index) const;
  void set_lfoot_ori(int index, float value);
  void add_lfoot_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      lfoot_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lfoot_ori();

  // repeated float rfoot_ori = 11;
  int rfoot_ori_size() const;
  void clear_rfoot_ori();
  static const int kRfootOriFieldNumber = 11;
  float rfoot_ori(int index) const;
  void set_rfoot_ori(int index, float value);
  void add_rfoot_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      rfoot_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rfoot_ori();

  // repeated float lfoot_rf_cmd = 12;
  int lfoot_rf_cmd_size() const;
  void clear_lfoot_rf_cmd();
  static const int kLfootRfCmdFieldNumber = 12;
  float lfoot_rf_cmd(int index) const;
  void set_lfoot_rf_cmd(int index, float value);
  void add_lfoot_rf_cmd(float value);
  const ::google::protobuf::RepeatedField< float >&
      lfoot_rf_cmd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lfoot_rf_cmd();

  // repeated float rfoot_rf_cmd = 13;
  int rfoot_rf_cmd_size() const;
  void clear_rfoot_rf_cmd();
  static const int kRfootRfCmdFieldNumber = 13;
  float rfoot_rf_cmd(int index) const;
  void set_rfoot_rf_cmd(int index, float value);
  void add_rfoot_rf_cmd(float value);
  const ::google::protobuf::RepeatedField< float >&
      rfoot_rf_cmd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rfoot_rf_cmd();

  // repeated float est_icp = 14;
  int est_icp_size() const;
  void clear_est_icp();
  static const int kEstIcpFieldNumber = 14;
  float est_icp(int index) const;
  void set_est_icp(int index, float value);
  void add_est_icp(float value);
  const ::google::protobuf::RepeatedField< float >&
      est_icp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_est_icp();

  // repeated float des_icp = 15;
  int des_icp_size() const;
  void clear_des_icp();
  static const int kDesIcpFieldNumber = 15;
  float des_icp(int index) const;
  void set_des_icp(int index, float value);
  void add_des_icp(float value);
  const ::google::protobuf::RepeatedField< float >&
      des_icp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_des_icp();

  // repeated float des_cmp = 16;
  int des_cmp_size() const;
  void clear_des_cmp();
  static const int kDesCmpFieldNumber = 16;
  float des_cmp(int index) const;
  void set_des_cmp(int index, float value);
  void add_des_cmp(float value);
  const ::google::protobuf::RepeatedField< float >&
      des_cmp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_des_cmp();

  // repeated float com_xy_weight = 17;
  int com_xy_weight_size() const;
  void clear_com_xy_weight();
  static const int kComXyWeightFieldNumber = 17;
  float com_xy_weight(int index) const;
  void set_com_xy_weight(int index, float value);
  void add_com_xy_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      com_xy_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_com_xy_weight();

  // repeated float com_xy_kp = 18;
  int com_xy_kp_size() const;
  void clear_com_xy_kp();
  static const int kComXyKpFieldNumber = 18;
  float com_xy_kp(int index) const;
  void set_com_xy_kp(int index, float value);
  void add_com_xy_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      com_xy_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_com_xy_kp();

  // repeated float com_xy_kd = 19;
  int com_xy_kd_size() const;
  void clear_com_xy_kd();
  static const int kComXyKdFieldNumber = 19;
  float com_xy_kd(int index) const;
  void set_com_xy_kd(int index, float value);
  void add_com_xy_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      com_xy_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_com_xy_kd();

  // repeated float com_xy_ki = 20;
  int com_xy_ki_size() const;
  void clear_com_xy_ki();
  static const int kComXyKiFieldNumber = 20;
  float com_xy_ki(int index) const;
  void set_com_xy_ki(int index, float value);
  void add_com_xy_ki(float value);
  const ::google::protobuf::RepeatedField< float >&
      com_xy_ki() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_com_xy_ki();

  // repeated float torso_ori_weight = 24;
  int torso_ori_weight_size() const;
  void clear_torso_ori_weight();
  static const int kTorsoOriWeightFieldNumber = 24;
  float torso_ori_weight(int index) const;
  void set_torso_ori_weight(int index, float value);
  void add_torso_ori_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      torso_ori_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_torso_ori_weight();

  // repeated float torso_ori_kp = 25;
  int torso_ori_kp_size() const;
  void clear_torso_ori_kp();
  static const int kTorsoOriKpFieldNumber = 25;
  float torso_ori_kp(int index) const;
  void set_torso_ori_kp(int index, float value);
  void add_torso_ori_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      torso_ori_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_torso_ori_kp();

  // repeated float torso_ori_kd = 26;
  int torso_ori_kd_size() const;
  void clear_torso_ori_kd();
  static const int kTorsoOriKdFieldNumber = 26;
  float torso_ori_kd(int index) const;
  void set_torso_ori_kd(int index, float value);
  void add_torso_ori_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      torso_ori_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_torso_ori_kd();

  // repeated float lf_pos_weight = 27;
  int lf_pos_weight_size() const;
  void clear_lf_pos_weight();
  static const int kLfPosWeightFieldNumber = 27;
  float lf_pos_weight(int index) const;
  void set_lf_pos_weight(int index, float value);
  void add_lf_pos_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_pos_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_pos_weight();

  // repeated float lf_pos_kp = 28;
  int lf_pos_kp_size() const;
  void clear_lf_pos_kp();
  static const int kLfPosKpFieldNumber = 28;
  float lf_pos_kp(int index) const;
  void set_lf_pos_kp(int index, float value);
  void add_lf_pos_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_pos_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_pos_kp();

  // repeated float lf_pos_kd = 29;
  int lf_pos_kd_size() const;
  void clear_lf_pos_kd();
  static const int kLfPosKdFieldNumber = 29;
  float lf_pos_kd(int index) const;
  void set_lf_pos_kd(int index, float value);
  void add_lf_pos_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_pos_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_pos_kd();

  // repeated float rf_pos_weight = 30;
  int rf_pos_weight_size() const;
  void clear_rf_pos_weight();
  static const int kRfPosWeightFieldNumber = 30;
  float rf_pos_weight(int index) const;
  void set_rf_pos_weight(int index, float value);
  void add_rf_pos_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_pos_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_pos_weight();

  // repeated float rf_pos_kp = 31;
  int rf_pos_kp_size() const;
  void clear_rf_pos_kp();
  static const int kRfPosKpFieldNumber = 31;
  float rf_pos_kp(int index) const;
  void set_rf_pos_kp(int index, float value);
  void add_rf_pos_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_pos_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_pos_kp();

  // repeated float rf_pos_kd = 32;
  int rf_pos_kd_size() const;
  void clear_rf_pos_kd();
  static const int kRfPosKdFieldNumber = 32;
  float rf_pos_kd(int index) const;
  void set_rf_pos_kd(int index, float value);
  void add_rf_pos_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_pos_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_pos_kd();

  // repeated float lf_ori_weight = 33;
  int lf_ori_weight_size() const;
  void clear_lf_ori_weight();
  static const int kLfOriWeightFieldNumber = 33;
  float lf_ori_weight(int index) const;
  void set_lf_ori_weight(int index, float value);
  void add_lf_ori_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_ori_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_ori_weight();

  // repeated float lf_ori_kp = 34;
  int lf_ori_kp_size() const;
  void clear_lf_ori_kp();
  static const int kLfOriKpFieldNumber = 34;
  float lf_ori_kp(int index) const;
  void set_lf_ori_kp(int index, float value);
  void add_lf_ori_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_ori_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_ori_kp();

  // repeated float lf_ori_kd = 35;
  int lf_ori_kd_size() const;
  void clear_lf_ori_kd();
  static const int kLfOriKdFieldNumber = 35;
  float lf_ori_kd(int index) const;
  void set_lf_ori_kd(int index, float value);
  void add_lf_ori_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      lf_ori_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lf_ori_kd();

  // repeated float rf_ori_weight = 36;
  int rf_ori_weight_size() const;
  void clear_rf_ori_weight();
  static const int kRfOriWeightFieldNumber = 36;
  float rf_ori_weight(int index) const;
  void set_rf_ori_weight(int index, float value);
  void add_rf_ori_weight(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_ori_weight() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_ori_weight();

  // repeated float rf_ori_kp = 37;
  int rf_ori_kp_size() const;
  void clear_rf_ori_kp();
  static const int kRfOriKpFieldNumber = 37;
  float rf_ori_kp(int index) const;
  void set_rf_ori_kp(int index, float value);
  void add_rf_ori_kp(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_ori_kp() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_ori_kp();

  // repeated float rf_ori_kd = 38;
  int rf_ori_kd_size() const;
  void clear_rf_ori_kd();
  static const int kRfOriKdFieldNumber = 38;
  float rf_ori_kd(int index) const;
  void set_rf_ori_kd(int index, float value);
  void add_rf_ori_kd(float value);
  const ::google::protobuf::RepeatedField< float >&
      rf_ori_kd() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rf_ori_kd();

  // repeated float kf_base_joint_pos = 39;
  int kf_base_joint_pos_size() const;
  void clear_kf_base_joint_pos();
  static const int kKfBaseJointPosFieldNumber = 39;
  float kf_base_joint_pos(int index) const;
  void set_kf_base_joint_pos(int index, float value);
  void add_kf_base_joint_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      kf_base_joint_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_kf_base_joint_pos();

  // repeated float kf_base_joint_ori = 40;
  int kf_base_joint_ori_size() const;
  void clear_kf_base_joint_ori();
  static const int kKfBaseJointOriFieldNumber = 40;
  float kf_base_joint_ori(int index) const;
  void set_kf_base_joint_ori(int index, float value);
  void add_kf_base_joint_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      kf_base_joint_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_kf_base_joint_ori();

  // float time = 1;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  float time() const;
  void set_time(float value);

  // uint32 phase = 2;
  void clear_phase();
  static const int kPhaseFieldNumber = 2;
  ::google::protobuf::uint32 phase() const;
  void set_phase(::google::protobuf::uint32 value);

  // float com_z_weight = 21;
  void clear_com_z_weight();
  static const int kComZWeightFieldNumber = 21;
  float com_z_weight() const;
  void set_com_z_weight(float value);

  // float com_z_kp = 22;
  void clear_com_z_kp();
  static const int kComZKpFieldNumber = 22;
  float com_z_kp() const;
  void set_com_z_kp(float value);

  // float com_z_kd = 23;
  void clear_com_z_kd();
  static const int kComZKdFieldNumber = 23;
  float com_z_kd() const;
  void set_com_z_kd(float value);

  // @@protoc_insertion_point(class_scope:draco.pnc_msg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > est_base_joint_pos_;
  mutable int _est_base_joint_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > est_base_joint_ori_;
  mutable int _est_base_joint_ori_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > joint_positions_;
  mutable int _joint_positions_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > des_com_pos_;
  mutable int _des_com_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > act_com_pos_;
  mutable int _act_com_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lfoot_pos_;
  mutable int _lfoot_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rfoot_pos_;
  mutable int _rfoot_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lfoot_ori_;
  mutable int _lfoot_ori_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rfoot_ori_;
  mutable int _rfoot_ori_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lfoot_rf_cmd_;
  mutable int _lfoot_rf_cmd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rfoot_rf_cmd_;
  mutable int _rfoot_rf_cmd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > est_icp_;
  mutable int _est_icp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > des_icp_;
  mutable int _des_icp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > des_cmp_;
  mutable int _des_cmp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > com_xy_weight_;
  mutable int _com_xy_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > com_xy_kp_;
  mutable int _com_xy_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > com_xy_kd_;
  mutable int _com_xy_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > com_xy_ki_;
  mutable int _com_xy_ki_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > torso_ori_weight_;
  mutable int _torso_ori_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > torso_ori_kp_;
  mutable int _torso_ori_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > torso_ori_kd_;
  mutable int _torso_ori_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_pos_weight_;
  mutable int _lf_pos_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_pos_kp_;
  mutable int _lf_pos_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_pos_kd_;
  mutable int _lf_pos_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_pos_weight_;
  mutable int _rf_pos_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_pos_kp_;
  mutable int _rf_pos_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_pos_kd_;
  mutable int _rf_pos_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_ori_weight_;
  mutable int _lf_ori_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_ori_kp_;
  mutable int _lf_ori_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lf_ori_kd_;
  mutable int _lf_ori_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_ori_weight_;
  mutable int _rf_ori_weight_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_ori_kp_;
  mutable int _rf_ori_kp_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rf_ori_kd_;
  mutable int _rf_ori_kd_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > kf_base_joint_pos_;
  mutable int _kf_base_joint_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > kf_base_joint_ori_;
  mutable int _kf_base_joint_ori_cached_byte_size_;
  float time_;
  ::google::protobuf::uint32 phase_;
  float com_z_weight_;
  float com_z_kp_;
  float com_z_kd_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_draco_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class vr_teleop_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:draco.vr_teleop_msg) */ {
 public:
  vr_teleop_msg();
  virtual ~vr_teleop_msg();

  vr_teleop_msg(const vr_teleop_msg& from);

  inline vr_teleop_msg& operator=(const vr_teleop_msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  vr_teleop_msg(vr_teleop_msg&& from) noexcept
    : vr_teleop_msg() {
    *this = ::std::move(from);
  }

  inline vr_teleop_msg& operator=(vr_teleop_msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const vr_teleop_msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const vr_teleop_msg* internal_default_instance() {
    return reinterpret_cast<const vr_teleop_msg*>(
               &_vr_teleop_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(vr_teleop_msg* other);
  friend void swap(vr_teleop_msg& a, vr_teleop_msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline vr_teleop_msg* New() const final {
    return CreateMaybeMessage<vr_teleop_msg>(NULL);
  }

  vr_teleop_msg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<vr_teleop_msg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const vr_teleop_msg& from);
  void MergeFrom(const vr_teleop_msg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(vr_teleop_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float lh_pos = 1;
  int lh_pos_size() const;
  void clear_lh_pos();
  static const int kLhPosFieldNumber = 1;
  float lh_pos(int index) const;
  void set_lh_pos(int index, float value);
  void add_lh_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      lh_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lh_pos();

  // repeated float rh_pos = 2;
  int rh_pos_size() const;
  void clear_rh_pos();
  static const int kRhPosFieldNumber = 2;
  float rh_pos(int index) const;
  void set_rh_pos(int index, float value);
  void add_rh_pos(float value);
  const ::google::protobuf::RepeatedField< float >&
      rh_pos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rh_pos();

  // repeated float lh_ori = 3;
  int lh_ori_size() const;
  void clear_lh_ori();
  static const int kLhOriFieldNumber = 3;
  float lh_ori(int index) const;
  void set_lh_ori(int index, float value);
  void add_lh_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      lh_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lh_ori();

  // repeated float rh_ori = 4;
  int rh_ori_size() const;
  void clear_rh_ori();
  static const int kRhOriFieldNumber = 4;
  float rh_ori(int index) const;
  void set_rh_ori(int index, float value);
  void add_rh_ori(float value);
  const ::google::protobuf::RepeatedField< float >&
      rh_ori() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_rh_ori();

  // bool l_trigger = 5;
  void clear_l_trigger();
  static const int kLTriggerFieldNumber = 5;
  bool l_trigger() const;
  void set_l_trigger(bool value);

  // bool l_bump = 6;
  void clear_l_bump();
  static const int kLBumpFieldNumber = 6;
  bool l_bump() const;
  void set_l_bump(bool value);

  // bool l_button = 7;
  void clear_l_button();
  static const int kLButtonFieldNumber = 7;
  bool l_button() const;
  void set_l_button(bool value);

  // bool l_pad = 8;
  void clear_l_pad();
  static const int kLPadFieldNumber = 8;
  bool l_pad() const;
  void set_l_pad(bool value);

  // bool r_trigger = 9;
  void clear_r_trigger();
  static const int kRTriggerFieldNumber = 9;
  bool r_trigger() const;
  void set_r_trigger(bool value);

  // bool r_bump = 10;
  void clear_r_bump();
  static const int kRBumpFieldNumber = 10;
  bool r_bump() const;
  void set_r_bump(bool value);

  // bool r_button = 11;
  void clear_r_button();
  static const int kRButtonFieldNumber = 11;
  bool r_button() const;
  void set_r_button(bool value);

  // bool r_pad = 12;
  void clear_r_pad();
  static const int kRPadFieldNumber = 12;
  bool r_pad() const;
  void set_r_pad(bool value);

  // @@protoc_insertion_point(class_scope:draco.vr_teleop_msg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > lh_pos_;
  mutable int _lh_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rh_pos_;
  mutable int _rh_pos_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lh_ori_;
  mutable int _lh_ori_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > rh_ori_;
  mutable int _rh_ori_cached_byte_size_;
  bool l_trigger_;
  bool l_bump_;
  bool l_button_;
  bool l_pad_;
  bool r_trigger_;
  bool r_bump_;
  bool r_button_;
  bool r_pad_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_draco_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// pnc_msg

// float time = 1;
inline void pnc_msg::clear_time() {
  time_ = 0;
}
inline float pnc_msg::time() const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.time)
  return time_;
}
inline void pnc_msg::set_time(float value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:draco.pnc_msg.time)
}

// uint32 phase = 2;
inline void pnc_msg::clear_phase() {
  phase_ = 0u;
}
inline ::google::protobuf::uint32 pnc_msg::phase() const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.phase)
  return phase_;
}
inline void pnc_msg::set_phase(::google::protobuf::uint32 value) {
  
  phase_ = value;
  // @@protoc_insertion_point(field_set:draco.pnc_msg.phase)
}

// repeated float est_base_joint_pos = 3;
inline int pnc_msg::est_base_joint_pos_size() const {
  return est_base_joint_pos_.size();
}
inline void pnc_msg::clear_est_base_joint_pos() {
  est_base_joint_pos_.Clear();
}
inline float pnc_msg::est_base_joint_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.est_base_joint_pos)
  return est_base_joint_pos_.Get(index);
}
inline void pnc_msg::set_est_base_joint_pos(int index, float value) {
  est_base_joint_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.est_base_joint_pos)
}
inline void pnc_msg::add_est_base_joint_pos(float value) {
  est_base_joint_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.est_base_joint_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::est_base_joint_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.est_base_joint_pos)
  return est_base_joint_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_est_base_joint_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.est_base_joint_pos)
  return &est_base_joint_pos_;
}

// repeated float est_base_joint_ori = 4;
inline int pnc_msg::est_base_joint_ori_size() const {
  return est_base_joint_ori_.size();
}
inline void pnc_msg::clear_est_base_joint_ori() {
  est_base_joint_ori_.Clear();
}
inline float pnc_msg::est_base_joint_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.est_base_joint_ori)
  return est_base_joint_ori_.Get(index);
}
inline void pnc_msg::set_est_base_joint_ori(int index, float value) {
  est_base_joint_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.est_base_joint_ori)
}
inline void pnc_msg::add_est_base_joint_ori(float value) {
  est_base_joint_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.est_base_joint_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::est_base_joint_ori() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.est_base_joint_ori)
  return est_base_joint_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_est_base_joint_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.est_base_joint_ori)
  return &est_base_joint_ori_;
}

// repeated float joint_positions = 5;
inline int pnc_msg::joint_positions_size() const {
  return joint_positions_.size();
}
inline void pnc_msg::clear_joint_positions() {
  joint_positions_.Clear();
}
inline float pnc_msg::joint_positions(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.joint_positions)
  return joint_positions_.Get(index);
}
inline void pnc_msg::set_joint_positions(int index, float value) {
  joint_positions_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.joint_positions)
}
inline void pnc_msg::add_joint_positions(float value) {
  joint_positions_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.joint_positions)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::joint_positions() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.joint_positions)
  return joint_positions_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_joint_positions() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.joint_positions)
  return &joint_positions_;
}

// repeated float des_com_pos = 6;
inline int pnc_msg::des_com_pos_size() const {
  return des_com_pos_.size();
}
inline void pnc_msg::clear_des_com_pos() {
  des_com_pos_.Clear();
}
inline float pnc_msg::des_com_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.des_com_pos)
  return des_com_pos_.Get(index);
}
inline void pnc_msg::set_des_com_pos(int index, float value) {
  des_com_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.des_com_pos)
}
inline void pnc_msg::add_des_com_pos(float value) {
  des_com_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.des_com_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::des_com_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.des_com_pos)
  return des_com_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_des_com_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.des_com_pos)
  return &des_com_pos_;
}

// repeated float act_com_pos = 7;
inline int pnc_msg::act_com_pos_size() const {
  return act_com_pos_.size();
}
inline void pnc_msg::clear_act_com_pos() {
  act_com_pos_.Clear();
}
inline float pnc_msg::act_com_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.act_com_pos)
  return act_com_pos_.Get(index);
}
inline void pnc_msg::set_act_com_pos(int index, float value) {
  act_com_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.act_com_pos)
}
inline void pnc_msg::add_act_com_pos(float value) {
  act_com_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.act_com_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::act_com_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.act_com_pos)
  return act_com_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_act_com_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.act_com_pos)
  return &act_com_pos_;
}

// repeated float lfoot_pos = 8;
inline int pnc_msg::lfoot_pos_size() const {
  return lfoot_pos_.size();
}
inline void pnc_msg::clear_lfoot_pos() {
  lfoot_pos_.Clear();
}
inline float pnc_msg::lfoot_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lfoot_pos)
  return lfoot_pos_.Get(index);
}
inline void pnc_msg::set_lfoot_pos(int index, float value) {
  lfoot_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lfoot_pos)
}
inline void pnc_msg::add_lfoot_pos(float value) {
  lfoot_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lfoot_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lfoot_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lfoot_pos)
  return lfoot_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lfoot_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lfoot_pos)
  return &lfoot_pos_;
}

// repeated float rfoot_pos = 9;
inline int pnc_msg::rfoot_pos_size() const {
  return rfoot_pos_.size();
}
inline void pnc_msg::clear_rfoot_pos() {
  rfoot_pos_.Clear();
}
inline float pnc_msg::rfoot_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rfoot_pos)
  return rfoot_pos_.Get(index);
}
inline void pnc_msg::set_rfoot_pos(int index, float value) {
  rfoot_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rfoot_pos)
}
inline void pnc_msg::add_rfoot_pos(float value) {
  rfoot_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rfoot_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rfoot_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rfoot_pos)
  return rfoot_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rfoot_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rfoot_pos)
  return &rfoot_pos_;
}

// repeated float lfoot_ori = 10;
inline int pnc_msg::lfoot_ori_size() const {
  return lfoot_ori_.size();
}
inline void pnc_msg::clear_lfoot_ori() {
  lfoot_ori_.Clear();
}
inline float pnc_msg::lfoot_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lfoot_ori)
  return lfoot_ori_.Get(index);
}
inline void pnc_msg::set_lfoot_ori(int index, float value) {
  lfoot_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lfoot_ori)
}
inline void pnc_msg::add_lfoot_ori(float value) {
  lfoot_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lfoot_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lfoot_ori() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lfoot_ori)
  return lfoot_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lfoot_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lfoot_ori)
  return &lfoot_ori_;
}

// repeated float rfoot_ori = 11;
inline int pnc_msg::rfoot_ori_size() const {
  return rfoot_ori_.size();
}
inline void pnc_msg::clear_rfoot_ori() {
  rfoot_ori_.Clear();
}
inline float pnc_msg::rfoot_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rfoot_ori)
  return rfoot_ori_.Get(index);
}
inline void pnc_msg::set_rfoot_ori(int index, float value) {
  rfoot_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rfoot_ori)
}
inline void pnc_msg::add_rfoot_ori(float value) {
  rfoot_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rfoot_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rfoot_ori() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rfoot_ori)
  return rfoot_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rfoot_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rfoot_ori)
  return &rfoot_ori_;
}

// repeated float lfoot_rf_cmd = 12;
inline int pnc_msg::lfoot_rf_cmd_size() const {
  return lfoot_rf_cmd_.size();
}
inline void pnc_msg::clear_lfoot_rf_cmd() {
  lfoot_rf_cmd_.Clear();
}
inline float pnc_msg::lfoot_rf_cmd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lfoot_rf_cmd)
  return lfoot_rf_cmd_.Get(index);
}
inline void pnc_msg::set_lfoot_rf_cmd(int index, float value) {
  lfoot_rf_cmd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lfoot_rf_cmd)
}
inline void pnc_msg::add_lfoot_rf_cmd(float value) {
  lfoot_rf_cmd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lfoot_rf_cmd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lfoot_rf_cmd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lfoot_rf_cmd)
  return lfoot_rf_cmd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lfoot_rf_cmd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lfoot_rf_cmd)
  return &lfoot_rf_cmd_;
}

// repeated float rfoot_rf_cmd = 13;
inline int pnc_msg::rfoot_rf_cmd_size() const {
  return rfoot_rf_cmd_.size();
}
inline void pnc_msg::clear_rfoot_rf_cmd() {
  rfoot_rf_cmd_.Clear();
}
inline float pnc_msg::rfoot_rf_cmd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rfoot_rf_cmd)
  return rfoot_rf_cmd_.Get(index);
}
inline void pnc_msg::set_rfoot_rf_cmd(int index, float value) {
  rfoot_rf_cmd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rfoot_rf_cmd)
}
inline void pnc_msg::add_rfoot_rf_cmd(float value) {
  rfoot_rf_cmd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rfoot_rf_cmd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rfoot_rf_cmd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rfoot_rf_cmd)
  return rfoot_rf_cmd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rfoot_rf_cmd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rfoot_rf_cmd)
  return &rfoot_rf_cmd_;
}

// repeated float est_icp = 14;
inline int pnc_msg::est_icp_size() const {
  return est_icp_.size();
}
inline void pnc_msg::clear_est_icp() {
  est_icp_.Clear();
}
inline float pnc_msg::est_icp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.est_icp)
  return est_icp_.Get(index);
}
inline void pnc_msg::set_est_icp(int index, float value) {
  est_icp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.est_icp)
}
inline void pnc_msg::add_est_icp(float value) {
  est_icp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.est_icp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::est_icp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.est_icp)
  return est_icp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_est_icp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.est_icp)
  return &est_icp_;
}

// repeated float des_icp = 15;
inline int pnc_msg::des_icp_size() const {
  return des_icp_.size();
}
inline void pnc_msg::clear_des_icp() {
  des_icp_.Clear();
}
inline float pnc_msg::des_icp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.des_icp)
  return des_icp_.Get(index);
}
inline void pnc_msg::set_des_icp(int index, float value) {
  des_icp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.des_icp)
}
inline void pnc_msg::add_des_icp(float value) {
  des_icp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.des_icp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::des_icp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.des_icp)
  return des_icp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_des_icp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.des_icp)
  return &des_icp_;
}

// repeated float des_cmp = 16;
inline int pnc_msg::des_cmp_size() const {
  return des_cmp_.size();
}
inline void pnc_msg::clear_des_cmp() {
  des_cmp_.Clear();
}
inline float pnc_msg::des_cmp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.des_cmp)
  return des_cmp_.Get(index);
}
inline void pnc_msg::set_des_cmp(int index, float value) {
  des_cmp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.des_cmp)
}
inline void pnc_msg::add_des_cmp(float value) {
  des_cmp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.des_cmp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::des_cmp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.des_cmp)
  return des_cmp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_des_cmp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.des_cmp)
  return &des_cmp_;
}

// repeated float com_xy_weight = 17;
inline int pnc_msg::com_xy_weight_size() const {
  return com_xy_weight_.size();
}
inline void pnc_msg::clear_com_xy_weight() {
  com_xy_weight_.Clear();
}
inline float pnc_msg::com_xy_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_xy_weight)
  return com_xy_weight_.Get(index);
}
inline void pnc_msg::set_com_xy_weight(int index, float value) {
  com_xy_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_xy_weight)
}
inline void pnc_msg::add_com_xy_weight(float value) {
  com_xy_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.com_xy_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::com_xy_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.com_xy_weight)
  return com_xy_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_com_xy_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.com_xy_weight)
  return &com_xy_weight_;
}

// repeated float com_xy_kp = 18;
inline int pnc_msg::com_xy_kp_size() const {
  return com_xy_kp_.size();
}
inline void pnc_msg::clear_com_xy_kp() {
  com_xy_kp_.Clear();
}
inline float pnc_msg::com_xy_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_xy_kp)
  return com_xy_kp_.Get(index);
}
inline void pnc_msg::set_com_xy_kp(int index, float value) {
  com_xy_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_xy_kp)
}
inline void pnc_msg::add_com_xy_kp(float value) {
  com_xy_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.com_xy_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::com_xy_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.com_xy_kp)
  return com_xy_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_com_xy_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.com_xy_kp)
  return &com_xy_kp_;
}

// repeated float com_xy_kd = 19;
inline int pnc_msg::com_xy_kd_size() const {
  return com_xy_kd_.size();
}
inline void pnc_msg::clear_com_xy_kd() {
  com_xy_kd_.Clear();
}
inline float pnc_msg::com_xy_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_xy_kd)
  return com_xy_kd_.Get(index);
}
inline void pnc_msg::set_com_xy_kd(int index, float value) {
  com_xy_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_xy_kd)
}
inline void pnc_msg::add_com_xy_kd(float value) {
  com_xy_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.com_xy_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::com_xy_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.com_xy_kd)
  return com_xy_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_com_xy_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.com_xy_kd)
  return &com_xy_kd_;
}

// repeated float com_xy_ki = 20;
inline int pnc_msg::com_xy_ki_size() const {
  return com_xy_ki_.size();
}
inline void pnc_msg::clear_com_xy_ki() {
  com_xy_ki_.Clear();
}
inline float pnc_msg::com_xy_ki(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_xy_ki)
  return com_xy_ki_.Get(index);
}
inline void pnc_msg::set_com_xy_ki(int index, float value) {
  com_xy_ki_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_xy_ki)
}
inline void pnc_msg::add_com_xy_ki(float value) {
  com_xy_ki_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.com_xy_ki)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::com_xy_ki() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.com_xy_ki)
  return com_xy_ki_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_com_xy_ki() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.com_xy_ki)
  return &com_xy_ki_;
}

// float com_z_weight = 21;
inline void pnc_msg::clear_com_z_weight() {
  com_z_weight_ = 0;
}
inline float pnc_msg::com_z_weight() const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_z_weight)
  return com_z_weight_;
}
inline void pnc_msg::set_com_z_weight(float value) {
  
  com_z_weight_ = value;
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_z_weight)
}

// float com_z_kp = 22;
inline void pnc_msg::clear_com_z_kp() {
  com_z_kp_ = 0;
}
inline float pnc_msg::com_z_kp() const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_z_kp)
  return com_z_kp_;
}
inline void pnc_msg::set_com_z_kp(float value) {
  
  com_z_kp_ = value;
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_z_kp)
}

// float com_z_kd = 23;
inline void pnc_msg::clear_com_z_kd() {
  com_z_kd_ = 0;
}
inline float pnc_msg::com_z_kd() const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.com_z_kd)
  return com_z_kd_;
}
inline void pnc_msg::set_com_z_kd(float value) {
  
  com_z_kd_ = value;
  // @@protoc_insertion_point(field_set:draco.pnc_msg.com_z_kd)
}

// repeated float torso_ori_weight = 24;
inline int pnc_msg::torso_ori_weight_size() const {
  return torso_ori_weight_.size();
}
inline void pnc_msg::clear_torso_ori_weight() {
  torso_ori_weight_.Clear();
}
inline float pnc_msg::torso_ori_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.torso_ori_weight)
  return torso_ori_weight_.Get(index);
}
inline void pnc_msg::set_torso_ori_weight(int index, float value) {
  torso_ori_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.torso_ori_weight)
}
inline void pnc_msg::add_torso_ori_weight(float value) {
  torso_ori_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.torso_ori_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::torso_ori_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.torso_ori_weight)
  return torso_ori_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_torso_ori_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.torso_ori_weight)
  return &torso_ori_weight_;
}

// repeated float torso_ori_kp = 25;
inline int pnc_msg::torso_ori_kp_size() const {
  return torso_ori_kp_.size();
}
inline void pnc_msg::clear_torso_ori_kp() {
  torso_ori_kp_.Clear();
}
inline float pnc_msg::torso_ori_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.torso_ori_kp)
  return torso_ori_kp_.Get(index);
}
inline void pnc_msg::set_torso_ori_kp(int index, float value) {
  torso_ori_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.torso_ori_kp)
}
inline void pnc_msg::add_torso_ori_kp(float value) {
  torso_ori_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.torso_ori_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::torso_ori_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.torso_ori_kp)
  return torso_ori_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_torso_ori_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.torso_ori_kp)
  return &torso_ori_kp_;
}

// repeated float torso_ori_kd = 26;
inline int pnc_msg::torso_ori_kd_size() const {
  return torso_ori_kd_.size();
}
inline void pnc_msg::clear_torso_ori_kd() {
  torso_ori_kd_.Clear();
}
inline float pnc_msg::torso_ori_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.torso_ori_kd)
  return torso_ori_kd_.Get(index);
}
inline void pnc_msg::set_torso_ori_kd(int index, float value) {
  torso_ori_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.torso_ori_kd)
}
inline void pnc_msg::add_torso_ori_kd(float value) {
  torso_ori_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.torso_ori_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::torso_ori_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.torso_ori_kd)
  return torso_ori_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_torso_ori_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.torso_ori_kd)
  return &torso_ori_kd_;
}

// repeated float lf_pos_weight = 27;
inline int pnc_msg::lf_pos_weight_size() const {
  return lf_pos_weight_.size();
}
inline void pnc_msg::clear_lf_pos_weight() {
  lf_pos_weight_.Clear();
}
inline float pnc_msg::lf_pos_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_pos_weight)
  return lf_pos_weight_.Get(index);
}
inline void pnc_msg::set_lf_pos_weight(int index, float value) {
  lf_pos_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_pos_weight)
}
inline void pnc_msg::add_lf_pos_weight(float value) {
  lf_pos_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_pos_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_pos_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_pos_weight)
  return lf_pos_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_pos_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_pos_weight)
  return &lf_pos_weight_;
}

// repeated float lf_pos_kp = 28;
inline int pnc_msg::lf_pos_kp_size() const {
  return lf_pos_kp_.size();
}
inline void pnc_msg::clear_lf_pos_kp() {
  lf_pos_kp_.Clear();
}
inline float pnc_msg::lf_pos_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_pos_kp)
  return lf_pos_kp_.Get(index);
}
inline void pnc_msg::set_lf_pos_kp(int index, float value) {
  lf_pos_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_pos_kp)
}
inline void pnc_msg::add_lf_pos_kp(float value) {
  lf_pos_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_pos_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_pos_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_pos_kp)
  return lf_pos_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_pos_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_pos_kp)
  return &lf_pos_kp_;
}

// repeated float lf_pos_kd = 29;
inline int pnc_msg::lf_pos_kd_size() const {
  return lf_pos_kd_.size();
}
inline void pnc_msg::clear_lf_pos_kd() {
  lf_pos_kd_.Clear();
}
inline float pnc_msg::lf_pos_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_pos_kd)
  return lf_pos_kd_.Get(index);
}
inline void pnc_msg::set_lf_pos_kd(int index, float value) {
  lf_pos_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_pos_kd)
}
inline void pnc_msg::add_lf_pos_kd(float value) {
  lf_pos_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_pos_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_pos_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_pos_kd)
  return lf_pos_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_pos_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_pos_kd)
  return &lf_pos_kd_;
}

// repeated float rf_pos_weight = 30;
inline int pnc_msg::rf_pos_weight_size() const {
  return rf_pos_weight_.size();
}
inline void pnc_msg::clear_rf_pos_weight() {
  rf_pos_weight_.Clear();
}
inline float pnc_msg::rf_pos_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_pos_weight)
  return rf_pos_weight_.Get(index);
}
inline void pnc_msg::set_rf_pos_weight(int index, float value) {
  rf_pos_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_pos_weight)
}
inline void pnc_msg::add_rf_pos_weight(float value) {
  rf_pos_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_pos_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_pos_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_pos_weight)
  return rf_pos_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_pos_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_pos_weight)
  return &rf_pos_weight_;
}

// repeated float rf_pos_kp = 31;
inline int pnc_msg::rf_pos_kp_size() const {
  return rf_pos_kp_.size();
}
inline void pnc_msg::clear_rf_pos_kp() {
  rf_pos_kp_.Clear();
}
inline float pnc_msg::rf_pos_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_pos_kp)
  return rf_pos_kp_.Get(index);
}
inline void pnc_msg::set_rf_pos_kp(int index, float value) {
  rf_pos_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_pos_kp)
}
inline void pnc_msg::add_rf_pos_kp(float value) {
  rf_pos_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_pos_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_pos_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_pos_kp)
  return rf_pos_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_pos_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_pos_kp)
  return &rf_pos_kp_;
}

// repeated float rf_pos_kd = 32;
inline int pnc_msg::rf_pos_kd_size() const {
  return rf_pos_kd_.size();
}
inline void pnc_msg::clear_rf_pos_kd() {
  rf_pos_kd_.Clear();
}
inline float pnc_msg::rf_pos_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_pos_kd)
  return rf_pos_kd_.Get(index);
}
inline void pnc_msg::set_rf_pos_kd(int index, float value) {
  rf_pos_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_pos_kd)
}
inline void pnc_msg::add_rf_pos_kd(float value) {
  rf_pos_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_pos_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_pos_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_pos_kd)
  return rf_pos_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_pos_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_pos_kd)
  return &rf_pos_kd_;
}

// repeated float lf_ori_weight = 33;
inline int pnc_msg::lf_ori_weight_size() const {
  return lf_ori_weight_.size();
}
inline void pnc_msg::clear_lf_ori_weight() {
  lf_ori_weight_.Clear();
}
inline float pnc_msg::lf_ori_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_ori_weight)
  return lf_ori_weight_.Get(index);
}
inline void pnc_msg::set_lf_ori_weight(int index, float value) {
  lf_ori_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_ori_weight)
}
inline void pnc_msg::add_lf_ori_weight(float value) {
  lf_ori_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_ori_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_ori_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_ori_weight)
  return lf_ori_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_ori_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_ori_weight)
  return &lf_ori_weight_;
}

// repeated float lf_ori_kp = 34;
inline int pnc_msg::lf_ori_kp_size() const {
  return lf_ori_kp_.size();
}
inline void pnc_msg::clear_lf_ori_kp() {
  lf_ori_kp_.Clear();
}
inline float pnc_msg::lf_ori_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_ori_kp)
  return lf_ori_kp_.Get(index);
}
inline void pnc_msg::set_lf_ori_kp(int index, float value) {
  lf_ori_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_ori_kp)
}
inline void pnc_msg::add_lf_ori_kp(float value) {
  lf_ori_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_ori_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_ori_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_ori_kp)
  return lf_ori_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_ori_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_ori_kp)
  return &lf_ori_kp_;
}

// repeated float lf_ori_kd = 35;
inline int pnc_msg::lf_ori_kd_size() const {
  return lf_ori_kd_.size();
}
inline void pnc_msg::clear_lf_ori_kd() {
  lf_ori_kd_.Clear();
}
inline float pnc_msg::lf_ori_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.lf_ori_kd)
  return lf_ori_kd_.Get(index);
}
inline void pnc_msg::set_lf_ori_kd(int index, float value) {
  lf_ori_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.lf_ori_kd)
}
inline void pnc_msg::add_lf_ori_kd(float value) {
  lf_ori_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.lf_ori_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::lf_ori_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.lf_ori_kd)
  return lf_ori_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_lf_ori_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.lf_ori_kd)
  return &lf_ori_kd_;
}

// repeated float rf_ori_weight = 36;
inline int pnc_msg::rf_ori_weight_size() const {
  return rf_ori_weight_.size();
}
inline void pnc_msg::clear_rf_ori_weight() {
  rf_ori_weight_.Clear();
}
inline float pnc_msg::rf_ori_weight(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_ori_weight)
  return rf_ori_weight_.Get(index);
}
inline void pnc_msg::set_rf_ori_weight(int index, float value) {
  rf_ori_weight_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_ori_weight)
}
inline void pnc_msg::add_rf_ori_weight(float value) {
  rf_ori_weight_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_ori_weight)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_ori_weight() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_ori_weight)
  return rf_ori_weight_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_ori_weight() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_ori_weight)
  return &rf_ori_weight_;
}

// repeated float rf_ori_kp = 37;
inline int pnc_msg::rf_ori_kp_size() const {
  return rf_ori_kp_.size();
}
inline void pnc_msg::clear_rf_ori_kp() {
  rf_ori_kp_.Clear();
}
inline float pnc_msg::rf_ori_kp(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_ori_kp)
  return rf_ori_kp_.Get(index);
}
inline void pnc_msg::set_rf_ori_kp(int index, float value) {
  rf_ori_kp_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_ori_kp)
}
inline void pnc_msg::add_rf_ori_kp(float value) {
  rf_ori_kp_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_ori_kp)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_ori_kp() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_ori_kp)
  return rf_ori_kp_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_ori_kp() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_ori_kp)
  return &rf_ori_kp_;
}

// repeated float rf_ori_kd = 38;
inline int pnc_msg::rf_ori_kd_size() const {
  return rf_ori_kd_.size();
}
inline void pnc_msg::clear_rf_ori_kd() {
  rf_ori_kd_.Clear();
}
inline float pnc_msg::rf_ori_kd(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.rf_ori_kd)
  return rf_ori_kd_.Get(index);
}
inline void pnc_msg::set_rf_ori_kd(int index, float value) {
  rf_ori_kd_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.rf_ori_kd)
}
inline void pnc_msg::add_rf_ori_kd(float value) {
  rf_ori_kd_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.rf_ori_kd)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::rf_ori_kd() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.rf_ori_kd)
  return rf_ori_kd_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_rf_ori_kd() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.rf_ori_kd)
  return &rf_ori_kd_;
}

// repeated float kf_base_joint_pos = 39;
inline int pnc_msg::kf_base_joint_pos_size() const {
  return kf_base_joint_pos_.size();
}
inline void pnc_msg::clear_kf_base_joint_pos() {
  kf_base_joint_pos_.Clear();
}
inline float pnc_msg::kf_base_joint_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.kf_base_joint_pos)
  return kf_base_joint_pos_.Get(index);
}
inline void pnc_msg::set_kf_base_joint_pos(int index, float value) {
  kf_base_joint_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.kf_base_joint_pos)
}
inline void pnc_msg::add_kf_base_joint_pos(float value) {
  kf_base_joint_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.kf_base_joint_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::kf_base_joint_pos() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.kf_base_joint_pos)
  return kf_base_joint_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_kf_base_joint_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.kf_base_joint_pos)
  return &kf_base_joint_pos_;
}

// repeated float kf_base_joint_ori = 40;
inline int pnc_msg::kf_base_joint_ori_size() const {
  return kf_base_joint_ori_.size();
}
inline void pnc_msg::clear_kf_base_joint_ori() {
  kf_base_joint_ori_.Clear();
}
inline float pnc_msg::kf_base_joint_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.pnc_msg.kf_base_joint_ori)
  return kf_base_joint_ori_.Get(index);
}
inline void pnc_msg::set_kf_base_joint_ori(int index, float value) {
  kf_base_joint_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.pnc_msg.kf_base_joint_ori)
}
inline void pnc_msg::add_kf_base_joint_ori(float value) {
  kf_base_joint_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.pnc_msg.kf_base_joint_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
pnc_msg::kf_base_joint_ori() const {
  // @@protoc_insertion_point(field_list:draco.pnc_msg.kf_base_joint_ori)
  return kf_base_joint_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
pnc_msg::mutable_kf_base_joint_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.pnc_msg.kf_base_joint_ori)
  return &kf_base_joint_ori_;
}

// -------------------------------------------------------------------

// vr_teleop_msg

// repeated float lh_pos = 1;
inline int vr_teleop_msg::lh_pos_size() const {
  return lh_pos_.size();
}
inline void vr_teleop_msg::clear_lh_pos() {
  lh_pos_.Clear();
}
inline float vr_teleop_msg::lh_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.lh_pos)
  return lh_pos_.Get(index);
}
inline void vr_teleop_msg::set_lh_pos(int index, float value) {
  lh_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.lh_pos)
}
inline void vr_teleop_msg::add_lh_pos(float value) {
  lh_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.vr_teleop_msg.lh_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
vr_teleop_msg::lh_pos() const {
  // @@protoc_insertion_point(field_list:draco.vr_teleop_msg.lh_pos)
  return lh_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
vr_teleop_msg::mutable_lh_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.vr_teleop_msg.lh_pos)
  return &lh_pos_;
}

// repeated float rh_pos = 2;
inline int vr_teleop_msg::rh_pos_size() const {
  return rh_pos_.size();
}
inline void vr_teleop_msg::clear_rh_pos() {
  rh_pos_.Clear();
}
inline float vr_teleop_msg::rh_pos(int index) const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.rh_pos)
  return rh_pos_.Get(index);
}
inline void vr_teleop_msg::set_rh_pos(int index, float value) {
  rh_pos_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.rh_pos)
}
inline void vr_teleop_msg::add_rh_pos(float value) {
  rh_pos_.Add(value);
  // @@protoc_insertion_point(field_add:draco.vr_teleop_msg.rh_pos)
}
inline const ::google::protobuf::RepeatedField< float >&
vr_teleop_msg::rh_pos() const {
  // @@protoc_insertion_point(field_list:draco.vr_teleop_msg.rh_pos)
  return rh_pos_;
}
inline ::google::protobuf::RepeatedField< float >*
vr_teleop_msg::mutable_rh_pos() {
  // @@protoc_insertion_point(field_mutable_list:draco.vr_teleop_msg.rh_pos)
  return &rh_pos_;
}

// repeated float lh_ori = 3;
inline int vr_teleop_msg::lh_ori_size() const {
  return lh_ori_.size();
}
inline void vr_teleop_msg::clear_lh_ori() {
  lh_ori_.Clear();
}
inline float vr_teleop_msg::lh_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.lh_ori)
  return lh_ori_.Get(index);
}
inline void vr_teleop_msg::set_lh_ori(int index, float value) {
  lh_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.lh_ori)
}
inline void vr_teleop_msg::add_lh_ori(float value) {
  lh_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.vr_teleop_msg.lh_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
vr_teleop_msg::lh_ori() const {
  // @@protoc_insertion_point(field_list:draco.vr_teleop_msg.lh_ori)
  return lh_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
vr_teleop_msg::mutable_lh_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.vr_teleop_msg.lh_ori)
  return &lh_ori_;
}

// repeated float rh_ori = 4;
inline int vr_teleop_msg::rh_ori_size() const {
  return rh_ori_.size();
}
inline void vr_teleop_msg::clear_rh_ori() {
  rh_ori_.Clear();
}
inline float vr_teleop_msg::rh_ori(int index) const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.rh_ori)
  return rh_ori_.Get(index);
}
inline void vr_teleop_msg::set_rh_ori(int index, float value) {
  rh_ori_.Set(index, value);
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.rh_ori)
}
inline void vr_teleop_msg::add_rh_ori(float value) {
  rh_ori_.Add(value);
  // @@protoc_insertion_point(field_add:draco.vr_teleop_msg.rh_ori)
}
inline const ::google::protobuf::RepeatedField< float >&
vr_teleop_msg::rh_ori() const {
  // @@protoc_insertion_point(field_list:draco.vr_teleop_msg.rh_ori)
  return rh_ori_;
}
inline ::google::protobuf::RepeatedField< float >*
vr_teleop_msg::mutable_rh_ori() {
  // @@protoc_insertion_point(field_mutable_list:draco.vr_teleop_msg.rh_ori)
  return &rh_ori_;
}

// bool l_trigger = 5;
inline void vr_teleop_msg::clear_l_trigger() {
  l_trigger_ = false;
}
inline bool vr_teleop_msg::l_trigger() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.l_trigger)
  return l_trigger_;
}
inline void vr_teleop_msg::set_l_trigger(bool value) {
  
  l_trigger_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.l_trigger)
}

// bool l_bump = 6;
inline void vr_teleop_msg::clear_l_bump() {
  l_bump_ = false;
}
inline bool vr_teleop_msg::l_bump() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.l_bump)
  return l_bump_;
}
inline void vr_teleop_msg::set_l_bump(bool value) {
  
  l_bump_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.l_bump)
}

// bool l_button = 7;
inline void vr_teleop_msg::clear_l_button() {
  l_button_ = false;
}
inline bool vr_teleop_msg::l_button() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.l_button)
  return l_button_;
}
inline void vr_teleop_msg::set_l_button(bool value) {
  
  l_button_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.l_button)
}

// bool l_pad = 8;
inline void vr_teleop_msg::clear_l_pad() {
  l_pad_ = false;
}
inline bool vr_teleop_msg::l_pad() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.l_pad)
  return l_pad_;
}
inline void vr_teleop_msg::set_l_pad(bool value) {
  
  l_pad_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.l_pad)
}

// bool r_trigger = 9;
inline void vr_teleop_msg::clear_r_trigger() {
  r_trigger_ = false;
}
inline bool vr_teleop_msg::r_trigger() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.r_trigger)
  return r_trigger_;
}
inline void vr_teleop_msg::set_r_trigger(bool value) {
  
  r_trigger_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.r_trigger)
}

// bool r_bump = 10;
inline void vr_teleop_msg::clear_r_bump() {
  r_bump_ = false;
}
inline bool vr_teleop_msg::r_bump() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.r_bump)
  return r_bump_;
}
inline void vr_teleop_msg::set_r_bump(bool value) {
  
  r_bump_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.r_bump)
}

// bool r_button = 11;
inline void vr_teleop_msg::clear_r_button() {
  r_button_ = false;
}
inline bool vr_teleop_msg::r_button() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.r_button)
  return r_button_;
}
inline void vr_teleop_msg::set_r_button(bool value) {
  
  r_button_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.r_button)
}

// bool r_pad = 12;
inline void vr_teleop_msg::clear_r_pad() {
  r_pad_ = false;
}
inline bool vr_teleop_msg::r_pad() const {
  // @@protoc_insertion_point(field_get:draco.vr_teleop_msg.r_pad)
  return r_pad_;
}
inline void vr_teleop_msg::set_r_pad(bool value) {
  
  r_pad_ = value;
  // @@protoc_insertion_point(field_set:draco.vr_teleop_msg.r_pad)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace draco

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_draco_2eproto
